### ISSUE TITLE
Installation fails to save: Attempted to change an objectId to one that's already known to the Offline Store.

### ISSUE THREAD

**Issue by alexblack** [parse-community/Parse-SDK-Android#267]
```
Non-fatal Exception: java.lang.Exception: java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store.
       at com.aadhk.woinvoice.util.ParseInit$2.then(ProGuard:195)
       at com.aadhk.woinvoice.util.ParseInit$2.then(ProGuard:173)
       at bolts.Task$15.run(ProGuard:839)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store.
       at com.parse.OfflineStore.updateObjectId(ProGuard:1468)
       at com.parse.ParseObject.notifyObjectIdChanged(ProGuard:1260)
       at com.parse.ParseObject.setState(ProGuard:738)
       at com.parse.ParseObject.setState(ProGuard:726)
       at com.parse.ParseObject$6.then(ProGuard:1407)
       at com.parse.ParseObject$6.then(ProGuard:1392)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.access$000(ProGuard:32)
       at bolts.Task$10.then(ProGuard:581)
       at bolts.Task$10.then(ProGuard:578)
       at bolts.Task.runContinuations(ProGuard:875)
       at bolts.Task.trySetError(ProGuard:929)
       at bolts.TaskCompletionSource.trySetError(ProGuard:46)
       at bolts.TaskCompletionSource.setError(ProGuard:71)
       at bolts.Task$15$1.then(ProGuard:854)
       at bolts.Task$15$1.then(ProGuard:843)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.access$000(ProGuard:32)
       at bolts.Task$10.then(ProGuard:581)
       at bolts.Task$10.then(ProGuard:578)
       at bolts.Task.runContinuations(ProGuard:875)
       at bolts.Task.trySetError(ProGuard:929)
       at bolts.TaskCompletionSource.trySetError(ProGuard:46)
       at bolts.TaskCompletionSource.setError(ProGuard:71)
       at bolts.Task$15$1.then(ProGuard:854)
       at bolts.Task$15$1.then(ProGuard:843)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.access$000(ProGuard:32)
       at bolts.Task$10.then(ProGuard:581)
       at bolts.Task$10.then(ProGuard:578)
       at bolts.Task.runContinuations(ProGuard:875)
       at bolts.Task.trySetError(ProGuard:929)
       at bolts.TaskCompletionSource.trySetError(ProGuard:46)
       at bolts.TaskCompletionSource.setError(ProGuard:71)
       at bolts.Task$15$1.then(ProGuard:854)
       at bolts.Task$15$1.then(ProGuard:843)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.continueWith(ProGuard:588)
       at bolts.Task.continueWith(ProGuard:599)
       at bolts.Task$15.run(ProGuard:843)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeAfterTask(ProGuard:830)
       at bolts.Task.access$100(ProGuard:32)
       at bolts.Task$11.then(ProGuard:635)
       at bolts.Task$11.then(ProGuard:632)
       at bolts.Task.runContinuations(ProGuard:875)
       at bolts.Task.trySetError(ProGuard:929)
       at bolts.TaskCompletionSource.trySetError(ProGuard:46)
       at bolts.TaskCompletionSource.setError(ProGuard:71)
       at bolts.Task$15$1.then(ProGuard:854)
       at bolts.Task$15$1.then(ProGuard:843)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.continueWith(ProGuard:588)
       at bolts.Task.continueWith(ProGuard:599)
       at bolts.Task$15.run(ProGuard:843)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeAfterTask(ProGuard:830)
       at bolts.Task.access$100(ProGuard:32)
       at bolts.Task$11.then(ProGuard:635)
       at bolts.Task$11.then(ProGuard:632)
       at bolts.Task.runContinuations(ProGuard:875)
       at bolts.Task.trySetResult(ProGuard:913)
       at bolts.TaskCompletionSource.trySetResult(ProGuard:39)
       at bolts.TaskCompletionSource.setResult(ProGuard:62)
       at bolts.Task$15$1.then(ProGuard:856)
       at bolts.Task$15$1.then(ProGuard:843)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.continueWith(ProGuard:588)
       at bolts.Task.continueWith(ProGuard:599)
       at bolts.Task$15.run(ProGuard:843)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeAfterTask(ProGuard:830)
       at bolts.Task.access$100(ProGuard:32)
       at bolts.Task$11.then(ProGuard:635)
       at bolts.Task$11.then(ProGuard:632)
       at bolts.Task.runContinuations(ProGuard:875)
       at bolts.Task.trySetResult(ProGuard:913)
       at bolts.TaskCompletionSource.trySetResult(ProGuard:39)
       at bolts.TaskCompletionSource.setResult(ProGuard:62)
       at bolts.Task$15$1.then(ProGuard:856)
       at bolts.Task$15$1.then(ProGuard:843)
       at bolts.Task$14.run(ProGuard:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(ProGuard:105)
       at bolts.Task.completeImmediately(ProGuard:789)
       at bolts.Task.continueWith(ProGuard:588)
       at bolts.Task.continueWith(ProGuard:599)
       at bolts.Task$15.run(ProGuard:843)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

Here is the info I captured:

```
msg columns className, objectId are not unique (code 19) 
createdat   Thu May 28 22:16:18 MESZ 2015 
name    installation.save-failed 
appversion  0.1.181 
installationid  12de10a7-0558-43e4-955e-096b9c0b935a 
idx 34 
devicetype  android 
objectid    39CaIPof9e 
runcount    235 
updatedat   Mon Nov 23 05:23:57 MEZ 2015 
```

Another:

```
msg Attempted to change an objectId to one that's already known to the Offline Store. 
abtest-template 1 
createdat   Mon Nov 23 10:56:19 EST 2015 
name    installation.save-failed 
appversion  0.1.181 
cdtest-paywall  1 
installationid  6d2923fd-8946-4a36-babe-3889dffe9f50 
idx 78 
devicetype  android 
objectid    FhRwI115GJ 
runcount    12 
updatedat   Tue Nov 24 13:12:28 EST 2015
```

And another:

```
msg Attempted to change an objectId to one that's already known to the Offline Store. 
abtest-template 0 
createdat   Mon Nov 23 13:02:53 NZDT 2015 
name    installation.save-failed 
appversion  0.1.181 
cdtest-paywall  1 
installationid  c8a29f3a-e63c-4865-9241-5e8d242d3031 
idx 43 
devicetype  android 
objectid    C8n83z7WL7 
runcount    7 
updatedat   Tue Nov 24 19:58:57 NZDT 2015 
```

**Comment by alexblack** [comment]
Hi @wangmengyan95 what more info would you like?  If you have any insight into how to reproduce this parse bug that would be super helpful.  It seems rather mysterious to me.

I've included the information I've captured from 3 different users who have experienced this issue, I'm happy to collect any further data you require.

**Comment by wangmengyan95** [comment]
Hi @alexblack, thanks for the quick response, I am trying to figure out what is the possible cause of this issue. I will update the information I need here.

**Comment by grantland** [comment]
This seems like it could be related to #267, but instead of saving a new `ParseInstallation` instance with the `installationId` from disk from a `ParseInstallation` that has failed to be read from LDS, the `ParseInstallation` in LDS is succeeding to be read at some point after the first read failed and the save on the new instance who's `objectId` is then being tracked by LDS so LDS throws an error when the save result returns.

**Comment by iRazvan** [comment]
I have the same bug, I don't know how to reproduce it. It keeps showing up in my crash tracking system. I am deleting the parse data manually from the disk and cache when the user logs out. The parse installation is also cleared from the cloud code.

**Comment by stepanov-standy** [comment]
Hi Folks,

Looks like I have similar issue. What is interesting that my android app has been in production for 3 month. And only during last 1 month I see such stack traces from real users in my bug report system:

java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store. at com.parse.OfflineStore.updateObjectId(OfflineStore.java:1468) at com.parse.ParseObject.notifyObjectIdChanged(ParseObject.java:1353) at com.parse.ParseObject.setState(ParseObject.java:751) at com.parse.ParseObject.setState(ParseObject.java:739) at com.parse.ParseObject$6.then(ParseObject.java:1500) at com.parse.ParseObject$6.then(ParseObject.java:1485) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.access$000(Task.java:32) at bolts.Task$10.then(Task.java:581) at bolts.Task$10.then(Task.java:578) at bolts.Task.runContinuations(Task.java:875) at bolts.Task.trySetError(Task.java:929) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:854) at bolts.Task$15$1.then(Task.java:843) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.access$000(Task.java:32) at bolts.Task$10.then(Task.java:581) at bolts.Task$10.then(Task.java:578) at bolts.Task.runContinuations(Task.java:875) at bolts.Task.trySetError(Task.java:929) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:854) at bolts.Task$15$1.then(Task.java:843) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.access$000(Task.java:32) at bolts.Task$10.then(Task.java:581) at bolts.Task$10.then(Task.java:578) at bolts.Task.runContinuations(Task.java:875) at bolts.Task.trySetError(Task.java:929) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:854) at bolts.Task$15$1.then(Task.java:843) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.continueWith(Task.java:588) at bolts.Task.continueWith(Task.java:599) at bolts.Task$15.run(Task.java:843) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:830) at bolts.Task.access$100(Task.java:32) at bolts.Task$11.then(Task.java:635) at bolts.Task$11.then(Task.java:632) at bolts.Task.runContinuations(Task.java:875) at bolts.Task.trySetError(Task.java:929) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:854) at bolts.Task$15$1.then(Task.java:843) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.continueWith(Task.java:588) at bolts.Task.continueWith(Task.java:599) at bolts.Task$15.run(Task.java:843) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:830) at bolts.Task.access$100(Task.java:32) at bolts.Task$11.then(Task.java:635) at bolts.Task$11.then(Task.java:632) at bolts.Task.runContinuations(Task.java:875) at bolts.Task.trySetResult(Task.java:913) at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39) at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62) at bolts.Task$15$1.then(Task.java:856) at bolts.Task$15$1.then(Task.java:843) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.continueWith(Task.java:588) at bolts.Task.continueWith(Task.java:599) at bolts.Task$15.run(Task.java:843) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:830) at bolts.Task.access$100(Task.java:32) at bolts.Task$11.then(Task.java:635) at bolts.Task$11.then(Task.java:632) at bolts.Task.runContinuations(Task.java:875) at bolts.Task.trySetResult(Task.java:913) at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39) at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62) at bolts.Task$15$1.then(Task.java:856) at bolts.Task$15$1.then(Task.java:843) at bolts.Task$14.run(Task.java:798) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:789) at bolts.Task.continueWith(Task.java:588) at bolts.Task.continueWith(Task.java:599) at bolts.Task$15.run(Task.java:843) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) at java.lang.Thread.run(Thread.java:838)

Unfortunately, I can't reproduce it locally on my test environments (emulators and real devices). Taking into account it's failure during async update of the offline mode, I can't say for sure what app actions cause this problem.

Parse Team, could you explain possible cases that may lead to such behaviour? Is it possible to ignore such exceptions that are currently fatal for my app and fully crash it. I've already tried to wrap biggest part of the methods where I store parse data in try/catch section, but it still fails. I am going to wrap ALL methods to see does it have any effect or not.

**Comment by stepanov-standy** [comment]
Hi Team, any updates on this? I don't want to disable parse in my app due to this small issue.

**Comment by mailat** [comment]
It is for sure a problem which is comming from Parse SDK. We use the latest version and we can see the same issue for some users on some instalations:

Fatal Exception: java.lang.RuntimeException: Unable to create application OurcoolApplication: java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4861)
       at android.app.ActivityThread.access$1500(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store.
       at com.parse.OfflineStore.updateObjectId(OfflineStore.java:1468)
       at com.parse.ParseObject.notifyObjectIdChanged(ParseObject.java:1260)
       at com.parse.ParseObject.setState(ParseObject.java:738)
       at com.parse.ParseObject.setState(ParseObject.java:726)
       at com.parse.ParseObject$6.then(ParseObject.java:1407)
       at com.parse.ParseObject$6.then(ParseObject.java:1392)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.access$000(Task.java:32)
       at bolts.Task$10.then(Task.java:581)
       at bolts.Task$10.then(Task.java:578)
       at bolts.Task.runContinuations(Task.java:875)
       at bolts.Task.trySetError(Task.java:929)
       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
       at bolts.Task$15$1.then(Task.java:854)
       at bolts.Task$15$1.then(Task.java:843)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.access$000(Task.java:32)
       at bolts.Task$10.then(Task.java:581)
       at bolts.Task$10.then(Task.java:578)
       at bolts.Task.runContinuations(Task.java:875)
       at bolts.Task.trySetError(Task.java:929)
       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
       at bolts.Task$15$1.then(Task.java:854)
       at bolts.Task$15$1.then(Task.java:843)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.access$000(Task.java:32)
       at bolts.Task$10.then(Task.java:581)
       at bolts.Task$10.then(Task.java:578)
       at bolts.Task.runContinuations(Task.java:875)
       at bolts.Task.trySetError(Task.java:929)
       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
       at bolts.Task$15$1.then(Task.java:854)
       at bolts.Task$15$1.then(Task.java:843)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.continueWith(Task.java:588)
       at bolts.Task.continueWith(Task.java:599)
       at bolts.Task$15.run(Task.java:843)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:830)
       at bolts.Task.access$100(Task.java:32)
       at bolts.Task$11.then(Task.java:635)
       at bolts.Task$11.then(Task.java:632)
       at bolts.Task.runContinuations(Task.java:875)
       at bolts.Task.trySetError(Task.java:929)
       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
       at bolts.Task$15$1.then(Task.java:854)
       at bolts.Task$15$1.then(Task.java:843)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.continueWith(Task.java:588)
       at bolts.Task.continueWith(Task.java:599)
       at bolts.Task$15.run(Task.java:843)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:830)
       at bolts.Task.access$100(Task.java:32)
       at bolts.Task$11.then(Task.java:635)
       at bolts.Task$11.then(Task.java:632)
       at bolts.Task.runContinuations(Task.java:875)
       at bolts.Task.trySetResult(Task.java:913)
       at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
       at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
       at bolts.Task$15$1.then(Task.java:856)
       at bolts.Task$15$1.then(Task.java:843)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.continueWith(Task.java:588)
       at bolts.Task.continueWith(Task.java:599)
       at bolts.Task$15.run(Task.java:843)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:830)
       at bolts.Task.access$100(Task.java:32)
       at bolts.Task$11.then(Task.java:635)
       at bolts.Task$11.then(Task.java:632)
       at bolts.Task.runContinuations(Task.java:875)
       at bolts.Task.trySetResult(Task.java:913)
       at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
       at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
       at bolts.Task$15$1.then(Task.java:856)
       at bolts.Task$15$1.then(Task.java:843)
       at bolts.Task$14.run(Task.java:798)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:789)
       at bolts.Task.continueWith(Task.java:588)
       at bolts.Task.continueWith(Task.java:599)
       at bolts.Task$15.run(Task.java:843)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by andrew8712** [comment]
I'm getting the same error when trying to save my PFUser:

    Attempted to change an objectId to one that's already known to the OfflineStore.

**Comment by alexblack** [comment]
Here is the LDS from a device that faces this issue

[ParseOfflineStore.zip](https://github.com/ParsePlatform/Parse-SDK-Android/files/100385/ParseOfflineStore.zip)

**Comment by stepanov-standy** [comment]
Parse Team, could you provide an ETA for the fix of the issue. It's pretty important for all of us, because it affects our users.

**Comment by grantland** [comment]
Could anyone confirm that this is still an issue with the latest version of the SDK (v1.13.0), an updated stack trace, and a small project that repros this issue with it?

**Comment by alexblack** [comment]
Is the LDS I shared from 1.12.0 useful at all?

**Comment by grantland** [comment]
All I was able to determine from that was there was not another ParseInstallation with the same objectId in SQLite.

**Comment by alexblack** [comment]
There is a fair amount of info on this thread.  A LDS capture, stack traces, example objects on your server that are having the problem.

Like the other Parse bugs I've hit I don't have any insights into how to reproduce this one.  I do have it reproducible right now on a device, if there is anything else you would like me to collect just let me know.

**Comment by stepanov-standy** [comment]
Hi Folks,

I have to confirm that even on 1.13 version the problem is reproducible :(

**Comment by alexblack** [comment]
"Like the other Parse bugs I've hit I don't have any insights into how to reproduce this one. I do have it reproducible right now on a device, if there is anything else you would like me to collect just let me know."

@grantland any thoughts?

**Comment by grantland** [comment]
@stepanov-standy would you be able to provide a small project and environment this issue reproduces on?

**Comment by grantland** [comment]
@alexblack i do not. this issue does not appear for us in any of our projects or environments so anything we could think of would be a shot in the dark. owners of the codebase that this reproduces are generally responsible for knowing how to reproduce it, since they have code that shows these symptoms.

**Comment by alexblack** [comment]
@grantland sorry I was asking if there was anything else you wanted me to collect from the device I have that repros the problem.

**Comment by alexblack** [comment]
"owners of the codebase that this reproduces are generally responsible for knowing how to reproduce it" Yes I'm aware of Parse's attitude towards its customers :)

I'm not sure about the other Parse users on this thread, but I certainly feel completely in the dark about how to reproduce these bizarre bugs.

My code is doing pretty straightforward things, like, saving the ParseInstallation object. Its not clear how you expect me to figure out from my code that saves an installation why your code is throwing this exception.

**Comment by grantland** [comment]
@alexblack grabbing data from a live production device isn't really a viable solution, since I'd need to step through methods in the SDK with the debugger. I could, however, do this if I had stable repro steps.

If this was the cause of something straightforward, it would be easy to isolate into a small project. This doesn't seem to be the case since none of those affected can reproduce it.

**Comment by alexblack** [comment]
@grantland I don't seem to see a response to my question. I have a decide that repros the problem, I managed to capture the LDS from it, is there anything you'd like me to capture from it that might help give us clues as to the problem?

eg logs, or values of variables, etc?  When we don't have a simple repro case steps like these are standard bug solving practice.

**Comment by grantland** [comment]
I answered this above:

> grabbing data from a live production device isn't really a viable solution, since I'd need to step through methods in the SDK with the debugger. I could, however, do this if I had stable repro steps.

Basically I need internal variables and possibly unattached object instances, which cannot be grabbed externally and reported.

The biggest problem is that without a repro we cannot prioritize this issue.

**Comment by alexblack** [comment]
Odd, I was expecting a yes or a no.

What if I ran the app with the Parse Android SDK source attached? I could then set breakpoints, and inspect things.

**Comment by grantland** [comment]
It was a no.

If you can reproduce it, why not isolate the problem and deliver a repro project?

**Comment by alexblack** [comment]
As I mentioned above, I'm in the dark about how to isolate the problem and reproduce it.

Given my new idea - attaching the debugger and running with the sources attached, is there anything useful I could grab for you?  Like internal variables etc.

**Comment by grantland** [comment]
I seem to be missing something. How are you offering to attach the debugger and grab me variables, etc. if you aren't able to reproduce the issue?

**Comment by alexblack** [comment]
I'm not sure what you're missing.  I have a device on which the issue repros.  I think I mentioned that above.

**Comment by alexblack** [comment]
Third time asking - I can attach the debugger and run with the sources attached, is there anything useful I could grab for you?

**Comment by grantland** [comment]
No, you did not mention that you can reproduce this. 

Debugging this over the internet is not scalable. If you're able to reproduce this, you can definitely isolate the issue. It's a simple process of scraping away code until you have the bare minimum that causes this issue.

I will not be spending any more time on this issue if you're not willing to spend the time to provide a repro.

**Comment by alexblack** [comment]
I never said I could reproduce this.  I assume by "reproduce this" you mean provide a simple project that demonstrates the problem.  If I've misunderstood please let me know.

I have mentioned several times that I have a device on which the problem reproduces (or, happens).  That is how I captured the LDS.  I was simply offering to grab some more info from it using the debugger to help us figure this one out.

> I will not be spending any more time on this issue if you're not willing to spend the time to provide a repro.

You seem to be confused.  Its not a matter of my willingness, I am very willing :)  I've asked several times for some suggestions from you on how to go about this, given that I am in the dark about your codebase.

**Comment by grantland** [comment]
> how to go about this

Figure out the triggers or actions that result in this error with your device. You're probably the only person in this thread that has access to a device that it occurs on, so the ball is in your court.

**Comment by alexblack** [comment]
I've already stated that the error occurs when ParseInstallation.saveInBackground is called.

**Comment by grantland** [comment]
That clearly isn't the only cause of it, since ParseInstallation.saveInBackground() succeeds on it's own.

**Comment by alexblack** [comment]
This problem happens on the device currently.  It happens when ParseInstallation.saveInBackground() is called.  I'm not sure what else you're looking for here regarding triggers or actions that result in this error with the device.

**Comment by grantland** [comment]
I'm looking for a project and/or steps that I can use to make this problem occur for me on my machine. I will not be responding to any more comments on this thread without a way to accomplish this.

**Comment by alexblack** [comment]
> I'm looking for a project and/or steps that I can use to make this problem occur for me on my machine

You've said that numerous times.  I simply asked for a pointer in the right direction given that I am not familiar with your codebase.

**Comment by alexblack** [comment]
> How are you offering to attach the debugger and grab me variables, etc. if you aren't able to reproduce the issue?

Did you figure out what you were missing?  I again was expecting a yes or no.

**Comment by stepanov-standy** [comment]
Hi There! Not able to reproduce the issue in synthetic test I've decided to replace all saveInBackground call to saveEventually. It was my assumption that problem was in saveInBackground. Now I can say that it was wrong. Nothing was changed after the replacement. I still have the same amount of crashes per day (on ~1100 sessions I have ~16-20 crashes). 

I've received dozens of comments from my users with ask to fix my app crashes, but I still can't reproduce required for the crash conditions on my real devices and emulators.

Does someone find a workaround for that problem?  What I can say for sure that the first incident with such problem was logged on Google Analytics on 14 November :(

<img width="1004" alt="screen shot 2016-02-19 at 10 50 23" src="https://cloud.githubusercontent.com/assets/12450499/13169456/b4dbb8ac-d6f6-11e5-8540-c5cd152e10a0.png">

**Comment by alexblack** [comment]
I wonder if resetting the installation might fix this up:

http://stackoverflow.com/questions/31890049/parse-push-notifications-how-to-reset-installation-data

**Comment by rogerhu** [comment]
I think we've fixed this issue in the last set of merges..

**Comment by stepanov-standy** [comment]
Rogerhu, awesome! Is it already part of 1.15.1 release? I am ready to test it on my users, because I have 10 app fails daily during last 1,5 year :)

**Comment by stepanov-standy** [comment]
Hm... looks like the issue still exists :(

I've updated to the latest 1.15.6, but still see the same fatal stacktraces from my users:

java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store. at com.parse.OfflineStore.updateObjectId(OfflineStore.java:1479) at com.parse.ParseObject.notifyObjectIdChanged(ParseObject.java:1322) at com.parse.ParseObject.setState(ParseObject.java:772) at com.parse.ParseObject.setState(ParseObject.java:760) at com.parse.ParseObject$6.then(ParseObject.java:1469) at com.parse.ParseObject$6.then(ParseObject.java:1454) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.access$000(Task.java:32) at bolts.Task$10.then(Task.java:654) at bolts.Task$10.then(Task.java:651) at bolts.Task.runContinuations(Task.java:956) at bolts.Task.trySetError(Task.java:1011) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:932) at bolts.Task$15$1.then(Task.java:921) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.access$000(Task.java:32) at bolts.Task$10.then(Task.java:654) at bolts.Task$10.then(Task.java:651) at bolts.Task.runContinuations(Task.java:956) at bolts.Task.trySetError(Task.java:1011) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:932) at bolts.Task$15$1.then(Task.java:921) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.access$000(Task.java:32) at bolts.Task$10.then(Task.java:654) at bolts.Task$10.then(Task.java:651) at bolts.Task.runContinuations(Task.java:956) at bolts.Task.trySetError(Task.java:1011) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:932) at bolts.Task$15$1.then(Task.java:921) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.continueWith(Task.java:661) at bolts.Task.continueWith(Task.java:672) at bolts.Task$15.run(Task.java:921) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:908) at bolts.Task.access$100(Task.java:32) at bolts.Task$11.then(Task.java:708) at bolts.Task$11.then(Task.java:705) at bolts.Task.runContinuations(Task.java:956) at bolts.Task.trySetError(Task.java:1011) at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46) at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71) at bolts.Task$15$1.then(Task.java:932) at bolts.Task$15$1.then(Task.java:921) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.continueWith(Task.java:661) at bolts.Task.continueWith(Task.java:672) at bolts.Task$15.run(Task.java:921) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:908) at bolts.Task.access$100(Task.java:32) at bolts.Task$11.then(Task.java:708) at bolts.Task$11.then(Task.java:705) at bolts.Task.runContinuations(Task.java:956) at bolts.Task.trySetResult(Task.java:994) at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39) at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62) at bolts.Task$15$1.then(Task.java:934) at bolts.Task$15$1.then(Task.java:921) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.continueWith(Task.java:661) at bolts.Task.continueWith(Task.java:672) at bolts.Task$15.run(Task.java:921) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:908) at bolts.Task.access$100(Task.java:32) at bolts.Task$11.then(Task.java:708) at bolts.Task$11.then(Task.java:705) at bolts.Task.runContinuations(Task.java:956) at bolts.Task.trySetResult(Task.java:994) at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39) at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62) at bolts.Task$15$1.then(Task.java:934) at bolts.Task$15$1.then(Task.java:921) at bolts.Task$14.run(Task.java:872) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeImmediately(Task.java:863) at bolts.Task.continueWith(Task.java:661) at bolts.Task.continueWith(Task.java:672) at bolts.Task$15.run(Task.java:921) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:761)

**Comment by venkataramanab** [comment]
I think you are creating new ParseObject with final type variable. Please check once.
