### ISSUE TITLE
[Android O] IllegalStateException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by cre8ivejp** [parse-community/Parse-SDK-Android#729]
Hi,

From Android O, background tasks must call `Context.startForegroundService` instead of `Context.startService`  ,but in this case you could just extend the `PushService` to `JobIntentService` to solve this.

Could you take a look at this issue please?

Migration guide:
https://developer.android.com/about/versions/oreo/android-8.0-changes.html#back-all

### Model
```
Device: Google Pixel
OS: Android 8.0.0
SDK Version : 1.15.8
```

### Error log
```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.parse.GcmBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTRATION flg=0x10 pkg=com.example.sample cmp=com.example.sample/com.parse.PushService (has extras) }: app is in background uid UidRecord{ac05be6 u0a187 TRNB idle procs:1 seq(0,0,0)}


Caused by java.lang.IllegalStateException
--
  | android.app.ContextImpl.startServiceCommon (ContextImpl.java:1505)
  | android.app.ContextImpl.startService (ContextImpl.java:1461)
  | android.content.ContextWrapper.startService (ContextWrapper.java:644)
  | android.content.ContextWrapper.startService (ContextWrapper.java:644)
  | com.parse.ServiceUtils.runIntentInService (ServiceUtils.java:37)
  | com.parse.ServiceUtils.runWakefulIntentInService (ServiceUtils.java:68)
  | com.parse.GcmBroadcastReceiver.onReceive (GcmBroadcastReceiver.java:23)
  | android.app.ActivityThread.handleReceiver (ActivityThread.java:3252)
  | android.app.ActivityThread.-wrap17 (Unknown Source)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1677)
  | android.os.Handler.dispatchMessage (Handler.java:105)
  | android.os.Looper.loop (Looper.java:164)
  | android.app.ActivityThread.main (ActivityThread.java:6541)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)


```

**Comment by natario1** [comment]
More in depth reference:
https://developer.android.com/about/versions/oreo/background.html

**Comment by flovilmart** [comment]
@natario1 any easy win to release a fix?

**Comment by natario1** [comment]
@flovilmart I am taking a look right now!

**Comment by flovilmart** [comment]
@natario1 YOU === awesome

**Comment by natario1** [comment]
@flovilmart what's your take on ripping out PPNS?

I understand it might be supported by someone out there, but it looks really a thing of the past and is a burden here, over code complexity and maintainance.

For example, from [wiki](https://github.com/parse-community/parse-server/wiki/PPNS-Protocol-Specification) : 

> In the Android SDK, the client sends a ping message to the server every 15 minutes using a coalesced timer that wakes the device from sleep if necessary.

If this was kind of bad practice before, now it is impossible with newer versions, it won't work. Not even sure anyone wants that. The platform way to wake up the device upon network requests is using FCM messages, which is where we are heading. Removing PPNS would help a lot, even in fixing this issue.. I'd be glad to do it.

**Comment by flovilmart** [comment]
I recall @jeacott1 was using it, but I’m not sure where it stands, the reference server implementation is available in GO, but Hasn’t seen maintenance for a while. Let’s open a PR with ripping it out, let it sink a bit and see where we go from there. Android O compat is more important than PPNS if I had to choose

**Comment by cre8ivejp** [comment]
I also agree about the PPNS.
Since my project only uses GCM I forked the project I made modifications for it to work.
Thank god I could release my app in time.

I was thinking to send a PR, but I was too busy with release this week and also I didn't know what to do with PPNS.

**Comment by rogerhu** [comment]
Let's pull it and someone who wants to support it can offer a PR to make it work on newer devices..

**Comment by cre8ivejp** [comment]
I was in a hurry so I only did the minimal changes to make it work.
You can take a look here:
https://github.com/cre8ivejp/Parse-SDK-Android/pull/1

**Comment by milosonator** [comment]
I get a ton of reported app crashes on android O, only to lead me here. I'm not very deep into the parse code, but is there any way to work around this issue?

**Comment by cre8ivejp** [comment]
For now there is no workaround for this.
If you can't wait for an approached solution and
if you don't use PPNS, you can check my PR as reference and adjust it to your needs or just use it.
I'm using it on my app for a week and so far so good.

https://github.com/cre8ivejp/Parse-SDK-Android/pull/1

**Comment by milosonator** [comment]
Thanks for your answer @cre8ivejp. Unfortunatly PPNS is important to my use case. Currently I'm investigating the issue in more detail, perhaps disabling PPNS on just Android O until I can get a better solution in place or there is a patch for parse android.

**Comment by Jawnnypoo** [comment]
For now, you can target/compile with API 25 instead

**Comment by milosonator** [comment]
@Jawnnypoo even if I already rolled out a version targeting API 26?

**Comment by flovilmart** [comment]
@milosonator, we’re gonna probably move forward and rip PPNS out for the sake of a fast delivery of the fix. If you wanna skip those version until you can provide a stable solution for PPNS, we’re more than happy to welcome your solution.

**Comment by natario1** [comment]
Should be fixed in #735 . If anyone with an Oreo device by hand, a set-up server etc. could test that branch (not only absence of crashes but also push delivery), it would be appreciated.

**Comment by flovilmart** [comment]
@mmimeault do we have some in the office yet?

**Comment by natario1** [comment]
Since we merged #735 you should be able to try `1.16.2-SNAPSHOT`. Would be cool to have confirmation that it's fixed before releasing

**Comment by johnnyzen** [comment]
will test now

**Comment by johnnyzen** [comment]
still getting the same crash on parse-android-1.16.2-20170910.070003-1

`java.lang.RuntimeException: Unable to start receiver com.parse.GcmBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent`

**Comment by natario1** [comment]
That does not seem to be the latest snapshot. Did you download that by hand or used `compile 'com.parse:parse-android:1.16.2-SNAPSHOT'`? You should try the latest, see https://oss.jfrog.org/artifactory/oss-snapshot-local/com/parse/parse-android/1.16.2-SNAPSHOT/ .

**Comment by johnnyzen** [comment]
hey @natario1 I downloaded the AAR, your right, it wasnt the latest.

So I tried parse-android-1.16.2-20170916.045736-2.aar

And getting a crash on starting the app:

`Unable to start receiver com.parse.GcmBroadcastReceiver: java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.xxx.xxx.xxx/com.parse.PushService} does not require android.permission.BIND_JOB_SERVICE permission`

**Comment by natario1** [comment]
Thanks @johnnyzen I have pushed a quick fix in #739 for that.

If you can / wish you can test out my branch. But if you are testing with a pre-Oreo device I don't see how you could end up there honestly. You should not even see the original Oreo crash at all, right?

**Comment by johnnyzen** [comment]
Thanks @natario1 sorry I meant 8.0... its been a long day...

Thanks for quick fix, will test now :)

**Comment by johnnyzen** [comment]
Hi @natario1 

Everything is working with your #739 fix. No crashes, push received ok when app closed, and also when app open.

Important! Just to let everyone know, if the app your building is targeting api 26, make sure your using channel ID's, otherwise the push wont show on device (it wont crash, but you will get an error saying no channel exists)
see: https://developer.android.com/guide/topics/ui/notifiers/notifications.html#CreateChannel

Many thanks @natario1

**Comment by jbekas** [comment]
I just wanted to chime in and say that the 20170916.180926-3 snapshot version is working for me as well. Thanks for the fix!

**Comment by natario1** [comment]
This has been released @jbekas

**Comment by FcoCGN** [comment]
I have received the same error since I upgraded to version 1.16.3 but on devices with versions less than Oreo:


Fatal Exception: java.lang.RuntimeException: Unable to start service com.parse.PushService@37d082b with Intent { act=com.google.android.c2dm.intent.REGISTRATION flg=0x10 pkg=com.package.example cmp=com.package.example/com.parse.PushService (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2951)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5348)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
       at com.parse.PushService.onStartCommand(PushService.java:239)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2934)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5348)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by riccardoch** [comment]
I've implemented the new version of Android SDK (1.16.3), added channels for devices with Android Oreo, but on those devices I received pushes only when the app is opened, while on previous versions of Android everything works perfectly. Have I to add something different in the manifest?
